						<?php
//
// File generated by ... on the 2018-05-30T17:13:35+0200
// Please do not edit manually
//

/**
 * Classes and menus for combodo-anonymizer (version 0.0.1)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

//
// Menus
//
class MenuCreation_combodo_anonymizer extends ModuleHandlerAPI
{
	public static function OnMenuCreation()
	{
		global $__comp_menus__; // ensure that the global variable is indeed global !
		$__comp_menus__['ConfigEditor'] = new WebPageMenuNode('ConfigEditor', utils::GetAbsoluteUrlModulePage('combodo-anonymizer', "config.php"), $__comp_menus__['AdminTools']->GetIndex(), 50 , 'ResourceAdminMenu', UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['ConfigAnonymizer'] = new WebPageMenuNode('ConfigAnonymizer', utils::GetAbsoluteUrlModulePage('combodo-anonymizer', "config.php"), $__comp_menus__['ConfigEditor']->GetIndex(), 10 , 'ResourceAdminMenu', UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
	}
} // class MenuCreation_combodo_anonymizer
